spring:
  profiles:
    active:
    - local

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #password: new1234!
    #url: jdbc:mariadb://localhost:3306/kvaram_ums 
    #username: kvaram_ums
    password: ENC(DJ5im/303Jmu8bmMsI5AkBDJ+xt0mLhD)
    url: ENC(mSVqYFxRMlsJAm1uS9Z5LBvc3axK5pjA/DqBgNoaadiyWy5wr6HZQc/0zghzbO/4ESj0gLLBhVY=)
    #username: ENC(CsesAk4Hb85fu0mnTs1xe/OBi8NWZF+p)    
    username: ENC(UR0g5WzoU7i7bxgCBBfsJffaQwBq9Ln1)
  kafka:
    #bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    bootstrap-servers: ENC(yHSKjD5HbST75P5m+bL1xfM74FMo+2WVigfjPY5w3sr0L9m7Y/noCPUfMTYiKfJML0hB4hsGHsI=)

kafka:
  my:
    push:
      topic:      
        name: app_push_topic
        
server:
  port: 8000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor



        
---
spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ENC(DJ5im/303Jmu8bmMsI5AkBDJ+xt0mLhD)
    url: ENC(mSVqYFxRMlsJAm1uS9Z5LBvc3axK5pjA/DqBgNoaadiyWy5wr6HZQc/0zghzbO/4ESj0gLLBhVY=)
    username: END(CsesAk4Hb85fu0mnTs1xe/OBi8NWZF+p)    
  kafka:
    #bootstrap-servers: 172.25.1.17:9092
    bootstrap-servers: ENC(oo/spYNhhk5ecrN4rf2xHr0dlINVYkJHt3lNyXMAsqY=)

kafka:
  my:
    push:
      topic:
        name: app_push_topic
        
server:
  port: 8080
  
jasypt:
  encryptor:
    bean: jasyptStringEncryptor 
  
---

spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ENC(DJ5im/303Jmu8bmMsI5AkBDJ+xt0mLhD)
    url: ENC(mSVqYFxRMlsJAm1uS9Z5LBvc3axK5pjA/DqBgNoaadiyWy5wr6HZQc/0zghzbO/4ESj0gLLBhVY=)
    username: END(CsesAk4Hb85fu0mnTs1xe/OBi8NWZF+p)    
  kafka:
    #bootstrap-servers: 172.25.1.71:9092,172.25.1.72:9092,172.25.1.73:9092
    bootstrap-servers: ENC(yeVctwmfDeWNECAyqyc8dLv11KNqFma/nyTrU4lHak9JdtQrvUZJEw5vXq+MuYqibP55dZGlmWOz/guLu/vgLQ==)

kafka:
  my:
    push:
      topic:
        name: app_push_topic
        
server:
  port: 8000
  
jasypt:
  encryptor:
    bean: jasyptStringEncryptor  
  

